spring.datasource.url=jdbc:mysql://localhost:3306/usermanagement
spring.datasource.username=usermanagement
spring.datasource.password=usermanagement

spring.jpa.hibernate.ddl-auto=update

application.mailing.frontend.activation-url=http://localhost:4200/activate-account
spring.mail.host=localhost

services.menu.url=http://localhost:8081
services.inventory.url=http://localhost:8082
services.order.url=http://localhost:8083