spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  application:
    name: apigateway

springdoc:
  default-produces-media-type: application/json
server:
#  servlet:
#    context-path: /api/v1/
  port: 8088

application:
  security:
    jwt:
      secret-key: 404E635266556A58633272357538782F413F4428472B4B6250645367566B5970F
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account