spring.application.name=apigateway
server.port=8088

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=50MB

springdoc.default-produces-media-type=application/json
  
application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=8640000

spring.mail.port=1025
spring.mail.username=cafe
spring.mail.password=cafe
spring.mail.properties.mail.smtp.trust=*
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.enabled=true