spring.datasource.url=jdbc:mysql://localhost:3306/usermanagement
spring.datasource.username=usermanagement
spring.datasource.password=usermanagement

spring.jpa.hibernate.ddl-auto=update

application.mailing.frontend.activation-url=http://localhost:4200/activate-account
spring.mail.host=localhost
