spring.application.name=order
server.port=8083

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.db.enabled=false